/**
 * BriefingCard Component
 *
 * Displays an AI-generated briefing for an ISS pass.
 * Uses TanStack DB collection for reactive briefing data.
 */

import {
	AlertTriangle,
	CheckCircle,
	Clock,
	CloudSun,
	Compass,
	Lightbulb,
	RefreshCw,
	Sparkles,
	X,
} from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useLocation } from "@/hooks/useLocation";
import { generateBriefing } from "@/lib/briefing/ai-client";
import { getBriefingByPassId, upsertBriefing } from "@/lib/briefing/collection";
import type { PassBriefing } from "@/lib/briefing/types";
import { getWeatherForPass } from "@/lib/briefing/weather";
import type { PassPrediction } from "@/lib/iss/types";

// =============================================================================
// TYPES
// =============================================================================

interface BriefingCardProps {
	pass: PassPrediction;
	className?: string;
	onClose?: () => void;
}

type BriefingStatus = "idle" | "generating" | "success" | "error";

// =============================================================================
// COMPONENT
// =============================================================================

/**
 * BriefingCard - Display AI-generated briefing with generation controls
 */
export function BriefingCard({
	pass,
	className = "",
	onClose,
}: BriefingCardProps) {
	const { coordinates } = useLocation();
	const cardRef = useRef<HTMLElement>(null);
	const previousStatusRef = useRef<BriefingStatus>("idle");

	// Local state for briefing data and status
	const [briefing, setBriefing] = useState<PassBriefing | null>(
		() => getBriefingByPassId(pass.id) ?? null,
	);
	const [status, setStatus] = useState<BriefingStatus>(
		briefing ? "success" : "idle",
	);
	const [error, setError] = useState<string | null>(null);
	const hasAutoGeneratedRef = useRef(false);

	// Reload briefing from cache when pass.id changes
	// Note: pass.id is now stable (hour-based), so it shouldn't change on recalculation
	useEffect(() => {
		const cachedBriefing = getBriefingByPassId(pass.id);

		if (cachedBriefing) {
			setBriefing(cachedBriefing);
			setStatus("success");
			setError(null);
		} else {
			setBriefing(null);
			setStatus("idle");
			hasAutoGeneratedRef.current = false; // Reset auto-generate flag for new pass
		}
	}, [pass.id]);

	// Keyboard navigation: Escape to close
	useEffect(() => {
		const handleKeyDown = (e: KeyboardEvent) => {
			if (e.key === "Escape" && onClose && status === "success") {
				onClose();
			}
		};

		document.addEventListener("keydown", handleKeyDown);
		return () => document.removeEventListener("keydown", handleKeyDown);
	}, [onClose, status]);

	// Focus trap: Keep focus within card when expanded
	useEffect(() => {
		if (status === "success" && cardRef.current) {
			const firstFocusable = cardRef.current.querySelector(
				'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
			) as HTMLElement | null;
			firstFocusable?.focus();
		}
	}, [status]);

	// Screen reader announcements for status changes
	useEffect(() => {
		if (previousStatusRef.current !== status) {
			previousStatusRef.current = status;
		}
	}, [status]);

	/**
	 * Generate or refresh the briefing
	 */
	const handleGenerate = useCallback(async () => {
		if (!coordinates) {
			setError("Location required to generate briefing");
			return;
		}

		setStatus("generating");
		setError(null);

		try {
			// Fetch weather client-side first to avoid server IP blocking
			let weather = null;
			try {
				weather = await getWeatherForPass(coordinates, pass.startTime);
			} catch (e) {
				console.warn("Client-side weather fetch failed:", e);
				// Continue without weather
			}

			const response = await generateBriefing({
				data: {
					passData: pass,
					location: coordinates,
					weather,
				},
			});

			if (response.status === "success") {
				setBriefing(response.briefing);
				upsertBriefing(response.briefing);
				setStatus("success");
			} else {
				setError(response.error);
				setStatus("error");
			}
		} catch (e) {
			console.error("Briefing generation failed:", e);
			setError("Failed to generate briefing");
			setStatus("error");
		}
	}, [coordinates, pass]);

	// Auto-generate briefing when card first appears if no cached briefing exists
	useEffect(() => {
		// Only auto-generate once per pass, and only if we have coordinates and no briefing
		if (
			status === "idle" &&
			!hasAutoGeneratedRef.current &&
			coordinates &&
			!briefing
		) {
			hasAutoGeneratedRef.current = true;
			handleGenerate();
		}
	}, [status, coordinates, briefing, handleGenerate]);

	/**
	 * Format time for display
	 */
	const formatTime = (date: Date) =>
		date.toLocaleTimeString("en-US", {
			hour: "numeric",
			minute: "2-digit",
			hour12: true,
		});

	/**
	 * Format date for display
	 */
	const formatDate = (date: Date) =>
		date.toLocaleDateString("en-US", {
			weekday: "short",
			month: "short",
			day: "numeric",
		});

	// =============================================================================
	// RENDER: IDLE STATE (No briefing yet)
	// =============================================================================

	if (status === "idle") {
		return (
			<article
				className={`bg-black/90 border border-matrix-dim p-4 backdrop-blur-sm ${className}`}
				aria-label={`Briefing options for pass on ${formatDate(pass.startTime)}`}
			>
				<div className="flex items-center justify-between mb-3">
					<div className="flex items-center gap-2 text-matrix-text">
						<Sparkles className="w-4 h-4" />
						<span className="text-xs font-bold uppercase tracking-wider">
							AI_Briefing
						</span>
					</div>
					{onClose && (
						<button
							type="button"
							onClick={onClose}
							className="text-matrix-dim hover:text-matrix-text"
							aria-label="Close briefing panel"
						>
							<X className="w-4 h-4" />
						</button>
					)}
				</div>

				<div className="text-center py-4">
					<p className="text-sm text-matrix-dim mb-4">
						Generate an AI briefing for this pass
					</p>
					<button
						type="button"
						onClick={handleGenerate}
						disabled={!coordinates}
						className="border border-matrix-text text-matrix-text hover:bg-matrix-text hover:text-black px-4 py-2 text-xs uppercase font-bold transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 mx-auto"
					>
						<Sparkles className="w-3 h-3" />
						Generate Briefing
					</button>
					{!coordinates && (
						<p className="text-[10px] text-matrix-alert mt-2">
							Set location first to generate briefing
						</p>
					)}
				</div>
			</article>
		);
	}

	// =============================================================================
	// RENDER: GENERATING STATE
	// =============================================================================

	if (status === "generating") {
		return (
			<article
				ref={cardRef}
				className={`bg-black/90 border border-matrix-dim p-4 backdrop-blur-sm ${className}`}
				aria-label="Generating briefing"
				aria-live="polite"
				aria-busy="true"
			>
				<div className="flex items-center justify-between mb-3">
					<div className="flex items-center gap-2 text-matrix-text">
						<Sparkles className="w-4 h-4 animate-pulse" />
						<span className="text-xs font-bold uppercase tracking-wider">
							AI_Briefing
						</span>
					</div>
				</div>

				<div className="text-center py-8">
					<RefreshCw className="w-8 h-8 text-matrix-text animate-spin mx-auto mb-3" />
					<p className="text-sm text-matrix-dim animate-pulse">
						GENERATING_BRIEFING...
					</p>
					<p className="text-[10px] text-matrix-dim mt-2">
						Analyzing orbital trajectory
					</p>
					{/* Skeleton loader for briefing content */}
					<div className="mt-6 space-y-3 text-left" aria-hidden="true">
						<div className="h-4 bg-matrix-dim/20 rounded w-full" />
						<div className="h-4 bg-matrix-dim/20 rounded w-5/6" />
						<div className="grid grid-cols-2 gap-2 mt-4">
							<div className="h-12 bg-matrix-dim/20 rounded" />
							<div className="h-12 bg-matrix-dim/20 rounded" />
						</div>
						<div className="h-20 bg-matrix-dim/20 rounded mt-2" />
					</div>
				</div>
			</article>
		);
	}

	// =============================================================================
	// RENDER: ERROR STATE
	// =============================================================================

	if (status === "error") {
		return (
			<div
				className={`bg-black/90 border border-matrix-alert/50 p-4 backdrop-blur-sm ${className}`}
				role="alert"
			>
				<div className="flex items-center justify-between mb-3">
					<div className="flex items-center gap-2 text-matrix-alert">
						<AlertTriangle className="w-4 h-4" />
						<span className="text-xs font-bold uppercase tracking-wider">
							Generation_Failed
						</span>
					</div>
					{onClose && (
						<button
							type="button"
							onClick={onClose}
							className="text-matrix-dim hover:text-matrix-text"
							aria-label="Close briefing panel"
						>
							<X className="w-4 h-4" />
						</button>
					)}
				</div>

				<p className="text-sm text-matrix-dim mb-4">
					{error || "An unexpected error occurred"}
				</p>

				<button
					type="button"
					onClick={handleGenerate}
					className="border border-matrix-text text-matrix-text hover:bg-matrix-text hover:text-black px-4 py-2 text-xs uppercase font-bold transition-colors flex items-center gap-2"
				>
					<RefreshCw className="w-3 h-3" />
					Retry
				</button>
			</div>
		);
	}

	// =============================================================================
	// RENDER: SUCCESS STATE (Briefing available)
	// =============================================================================

	if (!briefing) return null;

	return (
		<article
			ref={cardRef}
			className={`bg-black/90 border border-matrix-dim p-4 backdrop-blur-sm ${className}`}
			aria-label={`AI briefing for ISS pass on ${formatDate(pass.startTime)}`}
			aria-live="polite"
			tabIndex={-1}
		>
			{/* Header */}
			<div className="flex items-center justify-between mb-3 border-b border-matrix-dim/50 pb-2">
				<div className="flex items-center gap-2 text-matrix-text">
					<Sparkles className="w-4 h-4" />
					<span className="text-xs font-bold uppercase tracking-wider">
						AI_Briefing
					</span>
					<CheckCircle className="w-3 h-3 text-green-500" />
				</div>
				<div className="flex items-center gap-2">
					<button
						type="button"
						onClick={handleGenerate}
						className="text-matrix-dim hover:text-matrix-text focus:outline-none focus:ring-1 focus:ring-matrix-text"
						title="Refresh Briefing"
						aria-label="Refresh briefing"
					>
						<RefreshCw className="w-3 h-3" />
					</button>
					{onClose && (
						<button
							type="button"
							onClick={onClose}
							className="text-matrix-dim hover:text-matrix-text focus:outline-none focus:ring-1 focus:ring-matrix-text"
							aria-label="Close briefing panel"
						>
							<X className="w-4 h-4" />
						</button>
					)}
				</div>
			</div>

			{/* Summary */}
			<p className="text-sm text-matrix-text mb-3 font-medium">
				{briefing.summary}
			</p>

			{/* Key Info Grid */}
			<div className="grid grid-cols-2 gap-3 mb-4 text-[10px]">
				{/* Viewing Time */}
				<div className="flex items-start gap-2">
					<Clock className="w-3 h-3 text-matrix-dim shrink-0 mt-0.5" />
					<div>
						<span className="text-matrix-dim uppercase block">Start</span>
						<span className="text-matrix-text">
							{formatTime(briefing.viewingWindow.optimalStart)}
						</span>
					</div>
				</div>

				{/* Direction */}
				<div className="flex items-start gap-2">
					<Compass className="w-3 h-3 text-matrix-dim shrink-0 mt-0.5" />
					<div>
						<span className="text-matrix-dim uppercase block">Direction</span>
						<span className="text-matrix-text">
							{briefing.elevation.direction}
						</span>
					</div>
				</div>

				{/* Brightness */}
				<div className="flex items-start gap-2">
					<Sparkles className="w-3 h-3 text-matrix-dim shrink-0 mt-0.5" />
					<div>
						<span className="text-matrix-dim uppercase block">Brightness</span>
						<span className="text-matrix-text">
							{briefing.brightness.description}
						</span>
					</div>
				</div>

				{/* Weather (if available) */}
				{briefing.conditions && (
					<div className="flex items-start gap-2">
						<CloudSun
							className="w-3 h-3 text-matrix-dim shrink-0 mt-0.5"
							aria-hidden="true"
						/>
						<div className="flex-1">
							<span className="text-matrix-dim uppercase block">Weather</span>
							<div
								className="flex items-center gap-2"
								title={`${briefing.conditions.cloudCover}% cloud cover, ${Math.round(briefing.conditions.visibility / 1000)}km visibility, ${briefing.conditions.recommendation}`}
							>
								<span
									className={
										briefing.conditions.cloudCover < 50 &&
										briefing.conditions.visibility > 10000
											? "text-green-400"
											: briefing.conditions.cloudCover < 70
												? "text-yellow-400"
												: "text-orange-400"
									}
								>
									{briefing.conditions.cloudCover}% clouds
								</span>
								{briefing.conditions.cloudCover < 50 &&
									briefing.conditions.visibility > 10000 && (
										<span className="text-[9px] text-green-400 uppercase font-bold">
											✓ Favorable
										</span>
									)}
							</div>
							{briefing.conditions.recommendation && (
								<span className="text-[9px] text-matrix-dim block mt-0.5">
									{briefing.conditions.recommendation}
								</span>
							)}
						</div>
					</div>
				)}
			</div>

			{/* Narrative */}
			<div className="bg-matrix-dark/30 border border-matrix-dim/30 p-3 mb-4">
				<p className="text-xs text-matrix-dim leading-relaxed">
					{briefing.narrative}
				</p>
			</div>

			{/* Tips */}
			{briefing.tips.length > 0 && (
				<div>
					<div className="flex items-center gap-1 text-matrix-dim text-[10px] uppercase mb-2">
						<Lightbulb className="w-3 h-3" />
						<span>Viewing Tips</span>
					</div>
					<ul className="space-y-1">
						{briefing.tips.map((tip) => (
							<li
								key={tip}
								className="text-[10px] text-matrix-dim flex items-start gap-2"
							>
								<span className="text-matrix-text">▸</span>
								<span>{tip}</span>
							</li>
						))}
					</ul>
				</div>
			)}

			{/* Footer */}
			<div className="mt-4 pt-2 border-t border-matrix-dim/30 flex justify-between items-center text-[9px] text-matrix-dim">
				<span>
					Generated{" "}
					{new Date(briefing.generatedAt).toLocaleTimeString("en-US", {
						hour: "numeric",
						minute: "2-digit",
					})}
				</span>
				{!briefing.weatherIncluded && (
					<span className="text-yellow-500">Weather unavailable</span>
				)}
			</div>
		</article>
	);
}
