/**
 * ISS Tracker API Contracts
 * 
 * This file defines the TypeScript interfaces for all data structures
 * used in the ISS Tracker feature. These contracts serve as the source
 * of truth for type definitions during implementation.
 * 
 * @module iss-tracker/contracts
 */

// =============================================================================
// EXTERNAL API RESPONSE TYPES
// =============================================================================

/**
 * Response from Where The ISS At API
 * @see https://wheretheiss.at/w/developer
 */
export interface WTIAPositionResponse {
  name: string;
  id: number;
  latitude: number;
  longitude: number;
  altitude: number;
  velocity: number;
  visibility: 'daylight' | 'eclipsed';
  footprint: number;
  timestamp: number;
  daynum: number;
  solar_lat: number;
  solar_lon: number;
  units: string;
}

/**
 * Response from Open Notify ISS Position API (legacy fallback)
 * @see http://api.open-notify.org/iss-now.json
 */
export interface OpenNotifyPositionResponse {
  message: string;
  timestamp: number;
  iss_position: {
    latitude: string;  // Note: strings in legacy API
    longitude: string;
  };
}

/**
 * Response from Open Notify Crew API
 * @see http://api.open-notify.org/astros.json
 */
export interface OpenNotifyCrewResponse {
  message: string;
  number: number;
  people: Array<{
    name: string;
    craft: string;
  }>;
}

// =============================================================================
// CORE DOMAIN TYPES
// =============================================================================

/**
 * Normalized ISS position data used throughout the application
 * 
 * @remarks
 * The `id` field is required for TanStack DB's `getKey` function.
 * Generated from timestamp to enable position history tracking.
 */
export interface ISSPosition {
  /** Unique identifier for TanStack DB (timestamp-based) */
  id: string;
  /** Latitude in degrees (-90 to 90) */
  latitude: number;
  /** Longitude in degrees (-180 to 180) */
  longitude: number;
  /** Unix timestamp in seconds */
  timestamp: number;
  /** Altitude above Earth's surface in kilometers */
  altitude: number;
  /** Orbital velocity in kilometers per hour */
  velocity: number;
  /** Current lighting condition */
  visibility: string;
}

/**
 * Two-Line Element set for orbital calculations
 * @example
 * ["1 25544U 98067A   24140...", "2 25544  51.6396..."]
 */
export type TLEData = [line1: string, line2: string];

/**
 * Geographic coordinate pair
 */
export interface LatLng {
  /** Latitude in degrees */
  lat: number;
  /** Longitude in degrees */
  lng: number;
}

/**
 * 3D point on orbital path
 */
export interface OrbitalPoint {
  lat: number;
  lng: number;
  alt: number;
}

// =============================================================================
// CREW DATA TYPES
// =============================================================================

/**
 * Enriched astronaut profile with mission data
 * 
 * @remarks
 * The `id` field is required for TanStack DB's `getKey` function.
 * Generated by slugifying the astronaut's name.
 */
export interface Astronaut {
  /** Unique identifier for TanStack DB (slugified name) */
  id: string;
  /** Full name of astronaut */
  name: string;
  /** Spacecraft currently aboard ("ISS") */
  craft: string;
  /** Wikipedia portrait URL */
  image?: string;
  /** Mission role */
  role?: 'Commander' | 'Pilot' | 'Flight Engineer' | 'Mission Specialist' | string;
  /** Space agency affiliation */
  agency?: 'NASA' | 'Roscosmos' | 'ESA' | 'JAXA' | 'CSA' | string;
  /** Launch date ISO string (YYYY-MM-DD) */
  launchDate?: string;
  /** Expected return date ISO string */
  endDate?: string;
}

/**
 * Aggregated crew data response
 */
export interface CrewData {
  /** API response status */
  message: 'success' | 'error';
  /** Number of crew members */
  number: number;
  /** Array of astronaut profiles */
  people: Astronaut[];
}

/**
 * Local mission database profile for crew enrichment
 */
export interface MissionProfile {
  /** Launch date ISO string */
  start?: string;
  /** Expected return date ISO string */
  end?: string;
  /** Mission role */
  role: string;
  /** Space agency */
  agency?: string;
  /** Wikipedia image URL */
  image?: string;
  /** Alias reference to canonical name entry */
  aliasFor?: string;
}

// =============================================================================
// PREDICTION & CALCULATION TYPES
// =============================================================================

/**
 * Predicted ISS flyover for observer location
 * 
 * @remarks
 * The `id` field is required for TanStack DB's `getKey` function.
 * Generated from the pass start time.
 */
export interface PassPrediction {
  /** Unique identifier for TanStack DB (generated from startTime) */
  id: string;
  /** When the ISS rises above 10° elevation */
  startTime: Date;
  /** When the ISS drops below 10° elevation */
  endTime: Date;
  /** Maximum elevation angle in degrees */
  maxElevation: number;
  /** Duration of visible pass in minutes */
  duration: number;
  /** Array of points along the flyover arc */
  path: OrbitalPoint[];
}

/**
 * Keplerian orbital elements derived from TLE
 */
export interface OrbitalParameters {
  /** Orbital tilt relative to equator (degrees) */
  inclination: number;
  /** Orbital shape deviation from circle (0 = circular) */
  eccentricity: number;
  /** Orbits per day */
  meanMotion: number;
  /** Minutes per orbit */
  period: number;
  /** Highest point above Earth (km) */
  apogee: number;
  /** Lowest point above Earth (km) */
  perigee: number;
}

// =============================================================================
// CONTEXT & STATE TYPES
// =============================================================================

/**
 * Location context state for flyover predictions
 */
export interface LocationContextState {
  /** User's geographic location (null if not acquired) */
  userLocation: LatLng | null;
  /** Calculated next visible pass (null if none in 24h) */
  nextPass: PassPrediction | null;
  /** Whether pass calculation is in progress */
  isPredicting: boolean;
  /** Geolocation error message (null if no error) */
  error: string | null;
}

/**
 * Location context actions
 */
export interface LocationContextActions {
  /** Request browser geolocation */
  requestLocation: () => Promise<void>;
  /** Manually set location coordinates */
  manualLocation: (lat: number, lng: number) => void;
}

/**
 * Combined location context type
 */
export type LocationContextType = LocationContextState & LocationContextActions;

// =============================================================================
// UI COMPONENT PROPS
// =============================================================================

/**
 * Props for StatsPanel component
 */
export interface StatsPanelProps {
  data?: ISSPosition;
  isLoading: boolean;
}

/**
 * Props for MatrixText animated text component
 */
export interface MatrixTextProps {
  /** Text to display with scramble animation */
  text: string;
  /** Animation speed in milliseconds (default: 30) */
  speed?: number;
  /** Additional CSS classes */
  className?: string;
  /** Whether to preserve spaces during animation */
  preserveSpace?: boolean;
}

/**
 * Props for OrbitalSolver modal component
 */
export interface OrbitalSolverProps {
  /** TLE data for calculations */
  tle?: TLEData;
  /** Callback to close the modal */
  onClose: () => void;
}

/**
 * Props for CrewCard component
 */
export interface CrewCardProps {
  /** Astronaut data to display */
  astronaut: Astronaut;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Props for ScanlineOverlay component
 */
export interface ScanlineOverlayProps {
  /** Whether the overlay is visible */
  visible?: boolean;
  /** Additional CSS classes */
  className?: string;
}

// =============================================================================
// GLOBE VISUALIZATION TYPES
// =============================================================================

/**
 * Point data for react-globe.gl pointsData
 */
export interface GlobePoint {
  lat: number;
  lng: number;
  alt: number;
  radius: number;
  color: string;
  label: string;
}

/**
 * Ring data for react-globe.gl ringsData
 */
export interface GlobeRing {
  lat: number;
  lng: number;
  alt: number;
  maxR: number;
  propagationSpeed: number;
  repeatPeriod: number;
  color: string;
}

// =============================================================================
// TANSTACK QUERY DEFINITIONS (DB-Ready Architecture)
// =============================================================================

/**
 * Query factory for ISS data queries.
 * 
 * This pattern separates query configuration from components, making it easy
 * to swap the data source (API → TanStack DB) without changing component code.
 * 
 * ## TanStack DB Migration Path
 * 
 * The query keys and structure are designed to be compatible with
 * `@tanstack/query-db-collection`'s `queryCollectionOptions()`.
 * 
 * @example
 * // Phase 1: TanStack Query (current)
 * const { data } = useQuery(issQueries.currentPosition());
 * 
 * // Phase 2: TanStack DB (future)
 * // Replace useQuery with useLiveQuery, pointing to collection
 * const { data } = useLiveQuery((q) =>
 *   q.from({ pos: issPositionsCollection })
 *    .orderBy(({ pos }) => pos.timestamp, 'desc')
 *    .limit(1)
 * );
 * 
 * ## Key Requirements for DB Compatibility
 * 
 * 1. All entities have `id` field for `getKey: (item) => item.id`
 * 2. Collection queries return arrays (e.g., `Astronaut[]`)
 * 3. Query keys match future collection queryKey
 */
export interface ISSQueryFactory {
  /** 
   * Current ISS position (singleton, latest only)
   * For TanStack DB: derived from positions collection with orderBy/limit
   */
  currentPosition: () => {
    queryKey: readonly ['iss', 'position', 'current'];
    queryFn: FetchISSPositionFn;
    refetchInterval: number;
  };
  
  /** 
   * TLE orbital data - cached for 1 hour
   * Returns tuple [line1, line2], not a collection
   */
  tle: () => {
    queryKey: readonly ['iss', 'tle'];
    queryFn: FetchTLEFn;
    staleTime: number;
  };
  
  /** 
   * ISS crew manifest - collection of astronauts
   * Compatible with queryCollectionOptions({ queryKey: ['iss', 'crew'], ... })
   */
  crew: () => {
    queryKey: readonly ['iss', 'crew'];
    queryFn: () => Promise<Astronaut[]>;
    staleTime: number;
  };
}

/**
 * Helper to generate unique IDs for entities
 */
export const generateEntityId = {
  /** Generate position ID from timestamp */
  position: (timestamp: number): string => timestamp.toString(),
  
  /** Generate astronaut ID from name (slugified) */
  astronaut: (name: string): string => 
    name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
  
  /** Generate TLE ID from fetch timestamp */
  tle: (fetchTimestamp: number): string => `tle-${fetchTimestamp}`,
  
  /** Generate pass prediction ID from start time */
  pass: (startTime: Date): string => `pass-${startTime.getTime()}`,
}

// =============================================================================
// API FUNCTION SIGNATURES
// =============================================================================

/**
 * Fetch current ISS position from API
 * @returns Promise resolving to normalized position data
 * @throws Error if all API sources fail
 */
export type FetchISSPositionFn = () => Promise<ISSPosition>;

/**
 * Fetch current ISS crew from API
 * @returns Promise resolving to enriched crew data
 */
export type FetchCrewDataFn = () => Promise<CrewData>;

/**
 * Fetch TLE data from API
 * @returns Promise resolving to TLE tuple, falls back to hardcoded if APIs fail
 */
export type FetchTLEFn = () => Promise<TLEData>;

/**
 * Calculate orbital path from TLE
 * @param line1 - First TLE line
 * @param line2 - Second TLE line
 * @param startMins - Start time offset in minutes (negative for past)
 * @param endMins - End time offset in minutes
 * @param stepMins - Time step between points (default: 1)
 * @returns Array of orbital points
 */
export type CalculateOrbitPathFn = (
  line1: string,
  line2: string,
  startMins: number,
  endMins: number,
  stepMins?: number
) => OrbitalPoint[];

/**
 * Predict next visible ISS pass for observer
 * @param line1 - First TLE line
 * @param line2 - Second TLE line
 * @param userLoc - Observer's location
 * @returns PassPrediction or null if no pass within 24 hours
 */
export type PredictNextPassFn = (
  line1: string,
  line2: string,
  userLoc: LatLng
) => PassPrediction | null;

/**
 * Calculate Keplerian orbital parameters from TLE
 * @param line1 - First TLE line
 * @param line2 - Second TLE line
 * @returns OrbitalParameters or null if calculation fails
 */
export type CalculateOrbitalParametersFn = (
  line1: string,
  line2: string
) => OrbitalParameters | null;
