#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001 - ISS Copilot Cloudflare Deployment Bug Fix

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo "Installing dependencies..."
npm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development server..."

# Main service - TanStack Start with Cloudflare Workers
# Uses wrangler dev for local Cloudflare environment simulation
npm run dev &
wait_for_service 3000 "Development Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Development Server: http://localhost:3000"
echo "  Copilot Page:       http://localhost:3000/iss/copilot"
echo ""
echo "Useful Commands:"
echo "  npm run dev            # Start local development server"
echo "  npm run build          # Build for production"
echo "  npm run deploy         # Deploy to Cloudflare"
echo "  wrangler dev --remote  # Test with actual Cloudflare bindings"
echo ""
echo "Production URLs:"
echo "  https://ephemeris.observer"
echo "  https://ephemeris.observer/iss/copilot"
echo ""
