/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssIndexRouteImport } from './routes/iss/index'
import { Route as IssPassesRouteImport } from './routes/iss/passes'
import { Route as IssMapRouteImport } from './routes/iss/map'
import { Route as IssCrewRouteImport } from './routes/iss/crew'
import { Route as IssCopilotRouteImport } from './routes/iss/copilot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssIndexRoute = IssIndexRouteImport.update({
  id: '/iss/',
  path: '/iss/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssPassesRoute = IssPassesRouteImport.update({
  id: '/iss/passes',
  path: '/iss/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const IssMapRoute = IssMapRouteImport.update({
  id: '/iss/map',
  path: '/iss/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IssCrewRoute = IssCrewRouteImport.update({
  id: '/iss/crew',
  path: '/iss/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const IssCopilotRoute = IssCopilotRouteImport.update({
  id: '/iss/copilot',
  path: '/iss/copilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iss/copilot': typeof IssCopilotRoute
  '/iss/crew': typeof IssCrewRoute
  '/iss/map': typeof IssMapRoute
  '/iss/passes': typeof IssPassesRoute
  '/iss': typeof IssIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iss/copilot': typeof IssCopilotRoute
  '/iss/crew': typeof IssCrewRoute
  '/iss/map': typeof IssMapRoute
  '/iss/passes': typeof IssPassesRoute
  '/iss': typeof IssIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iss/copilot': typeof IssCopilotRoute
  '/iss/crew': typeof IssCrewRoute
  '/iss/map': typeof IssMapRoute
  '/iss/passes': typeof IssPassesRoute
  '/iss/': typeof IssIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iss/copilot'
    | '/iss/crew'
    | '/iss/map'
    | '/iss/passes'
    | '/iss'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/iss/copilot' | '/iss/crew' | '/iss/map' | '/iss/passes' | '/iss'
  id:
    | '__root__'
    | '/'
    | '/iss/copilot'
    | '/iss/crew'
    | '/iss/map'
    | '/iss/passes'
    | '/iss/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IssCopilotRoute: typeof IssCopilotRoute
  IssCrewRoute: typeof IssCrewRoute
  IssMapRoute: typeof IssMapRoute
  IssPassesRoute: typeof IssPassesRoute
  IssIndexRoute: typeof IssIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss/': {
      id: '/iss/'
      path: '/iss'
      fullPath: '/iss'
      preLoaderRoute: typeof IssIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss/passes': {
      id: '/iss/passes'
      path: '/iss/passes'
      fullPath: '/iss/passes'
      preLoaderRoute: typeof IssPassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss/map': {
      id: '/iss/map'
      path: '/iss/map'
      fullPath: '/iss/map'
      preLoaderRoute: typeof IssMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss/crew': {
      id: '/iss/crew'
      path: '/iss/crew'
      fullPath: '/iss/crew'
      preLoaderRoute: typeof IssCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss/copilot': {
      id: '/iss/copilot'
      path: '/iss/copilot'
      fullPath: '/iss/copilot'
      preLoaderRoute: typeof IssCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IssCopilotRoute: IssCopilotRoute,
  IssCrewRoute: IssCrewRoute,
  IssMapRoute: IssMapRoute,
  IssPassesRoute: IssPassesRoute,
  IssIndexRoute: IssIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
