/**
 * Copilot Route
 *
 * Route for the Observation Copilot chat interface.
 * Feature: 007-observation-copilot
 */

import { createFileRoute } from "@tanstack/react-router";
import { CopilotErrorBoundary } from "./-components/Copilot/BriefingErrorBoundary";
import { CopilotPanel } from "./-components/Copilot/CopilotPanel";
import { ISSLayout } from "./-components/ISSLayout";

// biome-ignore lint/suspicious/noExplicitAny: Route type will be generated by TanStack Router
export const Route = createFileRoute("/iss/copilot" as any)({
	component: CopilotPage,
	head: () => ({
		meta: [
			{
				title: "ISS Observation Copilot - Ephemeris",
			},
			{
				name: "description",
				content:
					"Ask questions about ISS passes, positions, weather conditions, and spaceflight facts using natural language.",
			},
		],
	}),
});

function CopilotPage() {
	return (
		<ISSLayout>
			<CopilotErrorBoundary>
				<div className="w-full h-full flex flex-col">
					<div className="border-b border-matrix-dim p-4 bg-matrix-dark">
						<h1 className="text-xl font-bold text-matrix-text">
							OBSERVATION COPILOT
						</h1>
						<p className="text-sm text-matrix-dim mt-1">
							Ask questions about ISS passes, positions, and spaceflight
						</p>
					</div>
					<div className="flex-1 overflow-hidden">
						<CopilotPanel />
					</div>
				</div>
			</CopilotErrorBoundary>
		</ISSLayout>
	);
}
